<?php
/**
 * ListOrdersRequestFilter
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WigandtTech\Refurbed\Model;

use \ArrayAccess;
use \WigandtTech\Refurbed\ObjectSerializer;

/**
 * ListOrdersRequestFilter Class Doc Comment
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ListOrdersRequestFilter implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ListOrdersRequest.Filter';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => '\WigandtTech\Refurbed\Model\Int64Filter',
        'releasedAt' => '\WigandtTech\Refurbed\Model\TimestampRangeFilter',
        'state' => '\WigandtTech\Refurbed\Model\OrderStateFilter',
        'labels' => '\WigandtTech\Refurbed\Model\OrderLabelCollectionFilter',
        'customerEmail' => '\WigandtTech\Refurbed\Model\OrderCustomerEmailFilter',
        'address' => '\WigandtTech\Refurbed\Model\OrderAddressFilter',
        'addressPhoneNumber' => '\WigandtTech\Refurbed\Model\OrderAddressPhoneNumberFilter',
        'shippingAddressEntity' => '\WigandtTech\Refurbed\Model\AddressEntityFilter',
        'shippingAddressCountryCode' => '\WigandtTech\Refurbed\Model\CountryCodeFilter',
        'invoiceAddress' => '\WigandtTech\Refurbed\Model\OrderAddressFilter',
        'invoiceAddressEntity' => '\WigandtTech\Refurbed\Model\AddressEntityFilter',
        'invoiceAddressVatin' => '\WigandtTech\Refurbed\Model\OrderAddressVATINFilter',
        'invoiceAddressCountryCode' => '\WigandtTech\Refurbed\Model\CountryCodeFilter',
        'currencyCode' => '\WigandtTech\Refurbed\Model\CurrencyCodeFilter',
        'settlementCurrencyCode' => '\WigandtTech\Refurbed\Model\CurrencyCodeFilter',
        'totalCharged' => '\WigandtTech\Refurbed\Model\NumericRangeFilter',
        'settlementTotalCharged' => '\WigandtTech\Refurbed\Model\NumericRangeFilter',
        'totalPaid' => '\WigandtTech\Refurbed\Model\NumericRangeFilter',
        'settlementTotalPaid' => '\WigandtTech\Refurbed\Model\NumericRangeFilter',
        'totalRefunded' => '\WigandtTech\Refurbed\Model\NumericRangeFilter',
        'settlementTotalRefunded' => '\WigandtTech\Refurbed\Model\NumericRangeFilter',
        'isInvoiceable' => '\WigandtTech\Refurbed\Model\BoolFilter',
        'hasInvoice' => '\WigandtTech\Refurbed\Model\BoolFilter',
        'itemName' => '\WigandtTech\Refurbed\Model\ListOrdersRequestFilterOrderItemNameFilter',
        'itemSku' => '\WigandtTech\Refurbed\Model\OfferSKUFilter',
        'itemOfferId' => '\WigandtTech\Refurbed\Model\Int64Filter'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'releasedAt' => null,
        'state' => null,
        'labels' => null,
        'customerEmail' => null,
        'address' => null,
        'addressPhoneNumber' => null,
        'shippingAddressEntity' => null,
        'shippingAddressCountryCode' => null,
        'invoiceAddress' => null,
        'invoiceAddressEntity' => null,
        'invoiceAddressVatin' => null,
        'invoiceAddressCountryCode' => null,
        'currencyCode' => null,
        'settlementCurrencyCode' => null,
        'totalCharged' => null,
        'settlementTotalCharged' => null,
        'totalPaid' => null,
        'settlementTotalPaid' => null,
        'totalRefunded' => null,
        'settlementTotalRefunded' => null,
        'isInvoiceable' => null,
        'hasInvoice' => null,
        'itemName' => null,
        'itemSku' => null,
        'itemOfferId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'releasedAt' => 'released_at',
        'state' => 'state',
        'labels' => 'labels',
        'customerEmail' => 'customer_email',
        'address' => 'address',
        'addressPhoneNumber' => 'address_phone_number',
        'shippingAddressEntity' => 'shipping_address_entity',
        'shippingAddressCountryCode' => 'shipping_address_country_code',
        'invoiceAddress' => 'invoice_address',
        'invoiceAddressEntity' => 'invoice_address_entity',
        'invoiceAddressVatin' => 'invoice_address_vatin',
        'invoiceAddressCountryCode' => 'invoice_address_country_code',
        'currencyCode' => 'currency_code',
        'settlementCurrencyCode' => 'settlement_currency_code',
        'totalCharged' => 'total_charged',
        'settlementTotalCharged' => 'settlement_total_charged',
        'totalPaid' => 'total_paid',
        'settlementTotalPaid' => 'settlement_total_paid',
        'totalRefunded' => 'total_refunded',
        'settlementTotalRefunded' => 'settlement_total_refunded',
        'isInvoiceable' => 'is_invoiceable',
        'hasInvoice' => 'has_invoice',
        'itemName' => 'item_name',
        'itemSku' => 'item_sku',
        'itemOfferId' => 'item_offer_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'releasedAt' => 'setReleasedAt',
        'state' => 'setState',
        'labels' => 'setLabels',
        'customerEmail' => 'setCustomerEmail',
        'address' => 'setAddress',
        'addressPhoneNumber' => 'setAddressPhoneNumber',
        'shippingAddressEntity' => 'setShippingAddressEntity',
        'shippingAddressCountryCode' => 'setShippingAddressCountryCode',
        'invoiceAddress' => 'setInvoiceAddress',
        'invoiceAddressEntity' => 'setInvoiceAddressEntity',
        'invoiceAddressVatin' => 'setInvoiceAddressVatin',
        'invoiceAddressCountryCode' => 'setInvoiceAddressCountryCode',
        'currencyCode' => 'setCurrencyCode',
        'settlementCurrencyCode' => 'setSettlementCurrencyCode',
        'totalCharged' => 'setTotalCharged',
        'settlementTotalCharged' => 'setSettlementTotalCharged',
        'totalPaid' => 'setTotalPaid',
        'settlementTotalPaid' => 'setSettlementTotalPaid',
        'totalRefunded' => 'setTotalRefunded',
        'settlementTotalRefunded' => 'setSettlementTotalRefunded',
        'isInvoiceable' => 'setIsInvoiceable',
        'hasInvoice' => 'setHasInvoice',
        'itemName' => 'setItemName',
        'itemSku' => 'setItemSku',
        'itemOfferId' => 'setItemOfferId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'releasedAt' => 'getReleasedAt',
        'state' => 'getState',
        'labels' => 'getLabels',
        'customerEmail' => 'getCustomerEmail',
        'address' => 'getAddress',
        'addressPhoneNumber' => 'getAddressPhoneNumber',
        'shippingAddressEntity' => 'getShippingAddressEntity',
        'shippingAddressCountryCode' => 'getShippingAddressCountryCode',
        'invoiceAddress' => 'getInvoiceAddress',
        'invoiceAddressEntity' => 'getInvoiceAddressEntity',
        'invoiceAddressVatin' => 'getInvoiceAddressVatin',
        'invoiceAddressCountryCode' => 'getInvoiceAddressCountryCode',
        'currencyCode' => 'getCurrencyCode',
        'settlementCurrencyCode' => 'getSettlementCurrencyCode',
        'totalCharged' => 'getTotalCharged',
        'settlementTotalCharged' => 'getSettlementTotalCharged',
        'totalPaid' => 'getTotalPaid',
        'settlementTotalPaid' => 'getSettlementTotalPaid',
        'totalRefunded' => 'getTotalRefunded',
        'settlementTotalRefunded' => 'getSettlementTotalRefunded',
        'isInvoiceable' => 'getIsInvoiceable',
        'hasInvoice' => 'getHasInvoice',
        'itemName' => 'getItemName',
        'itemSku' => 'getItemSku',
        'itemOfferId' => 'getItemOfferId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['releasedAt'] = $data['releasedAt'] ?? null;
        $this->container['state'] = $data['state'] ?? null;
        $this->container['labels'] = $data['labels'] ?? null;
        $this->container['customerEmail'] = $data['customerEmail'] ?? null;
        $this->container['address'] = $data['address'] ?? null;
        $this->container['addressPhoneNumber'] = $data['addressPhoneNumber'] ?? null;
        $this->container['shippingAddressEntity'] = $data['shippingAddressEntity'] ?? null;
        $this->container['shippingAddressCountryCode'] = $data['shippingAddressCountryCode'] ?? null;
        $this->container['invoiceAddress'] = $data['invoiceAddress'] ?? null;
        $this->container['invoiceAddressEntity'] = $data['invoiceAddressEntity'] ?? null;
        $this->container['invoiceAddressVatin'] = $data['invoiceAddressVatin'] ?? null;
        $this->container['invoiceAddressCountryCode'] = $data['invoiceAddressCountryCode'] ?? null;
        $this->container['currencyCode'] = $data['currencyCode'] ?? null;
        $this->container['settlementCurrencyCode'] = $data['settlementCurrencyCode'] ?? null;
        $this->container['totalCharged'] = $data['totalCharged'] ?? null;
        $this->container['settlementTotalCharged'] = $data['settlementTotalCharged'] ?? null;
        $this->container['totalPaid'] = $data['totalPaid'] ?? null;
        $this->container['settlementTotalPaid'] = $data['settlementTotalPaid'] ?? null;
        $this->container['totalRefunded'] = $data['totalRefunded'] ?? null;
        $this->container['settlementTotalRefunded'] = $data['settlementTotalRefunded'] ?? null;
        $this->container['isInvoiceable'] = $data['isInvoiceable'] ?? null;
        $this->container['hasInvoice'] = $data['hasInvoice'] ?? null;
        $this->container['itemName'] = $data['itemName'] ?? null;
        $this->container['itemSku'] = $data['itemSku'] ?? null;
        $this->container['itemOfferId'] = $data['itemOfferId'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return \WigandtTech\Refurbed\Model\Int64Filter|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param \WigandtTech\Refurbed\Model\Int64Filter|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets releasedAt
     *
     * @return \WigandtTech\Refurbed\Model\TimestampRangeFilter|null
     */
    public function getReleasedAt()
    {
        return $this->container['releasedAt'];
    }

    /**
     * Sets releasedAt
     *
     * @param \WigandtTech\Refurbed\Model\TimestampRangeFilter|null $releasedAt releasedAt
     *
     * @return self
     */
    public function setReleasedAt($releasedAt)
    {
        $this->container['releasedAt'] = $releasedAt;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \WigandtTech\Refurbed\Model\OrderStateFilter|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \WigandtTech\Refurbed\Model\OrderStateFilter|null $state state
     *
     * @return self
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return \WigandtTech\Refurbed\Model\OrderLabelCollectionFilter|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \WigandtTech\Refurbed\Model\OrderLabelCollectionFilter|null $labels labels
     *
     * @return self
     */
    public function setLabels($labels)
    {
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets customerEmail
     *
     * @return \WigandtTech\Refurbed\Model\OrderCustomerEmailFilter|null
     */
    public function getCustomerEmail()
    {
        return $this->container['customerEmail'];
    }

    /**
     * Sets customerEmail
     *
     * @param \WigandtTech\Refurbed\Model\OrderCustomerEmailFilter|null $customerEmail customerEmail
     *
     * @return self
     */
    public function setCustomerEmail($customerEmail)
    {
        $this->container['customerEmail'] = $customerEmail;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \WigandtTech\Refurbed\Model\OrderAddressFilter|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \WigandtTech\Refurbed\Model\OrderAddressFilter|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets addressPhoneNumber
     *
     * @return \WigandtTech\Refurbed\Model\OrderAddressPhoneNumberFilter|null
     */
    public function getAddressPhoneNumber()
    {
        return $this->container['addressPhoneNumber'];
    }

    /**
     * Sets addressPhoneNumber
     *
     * @param \WigandtTech\Refurbed\Model\OrderAddressPhoneNumberFilter|null $addressPhoneNumber addressPhoneNumber
     *
     * @return self
     */
    public function setAddressPhoneNumber($addressPhoneNumber)
    {
        $this->container['addressPhoneNumber'] = $addressPhoneNumber;

        return $this;
    }

    /**
     * Gets shippingAddressEntity
     *
     * @return \WigandtTech\Refurbed\Model\AddressEntityFilter|null
     */
    public function getShippingAddressEntity()
    {
        return $this->container['shippingAddressEntity'];
    }

    /**
     * Sets shippingAddressEntity
     *
     * @param \WigandtTech\Refurbed\Model\AddressEntityFilter|null $shippingAddressEntity shippingAddressEntity
     *
     * @return self
     */
    public function setShippingAddressEntity($shippingAddressEntity)
    {
        $this->container['shippingAddressEntity'] = $shippingAddressEntity;

        return $this;
    }

    /**
     * Gets shippingAddressCountryCode
     *
     * @return \WigandtTech\Refurbed\Model\CountryCodeFilter|null
     */
    public function getShippingAddressCountryCode()
    {
        return $this->container['shippingAddressCountryCode'];
    }

    /**
     * Sets shippingAddressCountryCode
     *
     * @param \WigandtTech\Refurbed\Model\CountryCodeFilter|null $shippingAddressCountryCode shippingAddressCountryCode
     *
     * @return self
     */
    public function setShippingAddressCountryCode($shippingAddressCountryCode)
    {
        $this->container['shippingAddressCountryCode'] = $shippingAddressCountryCode;

        return $this;
    }

    /**
     * Gets invoiceAddress
     *
     * @return \WigandtTech\Refurbed\Model\OrderAddressFilter|null
     */
    public function getInvoiceAddress()
    {
        return $this->container['invoiceAddress'];
    }

    /**
     * Sets invoiceAddress
     *
     * @param \WigandtTech\Refurbed\Model\OrderAddressFilter|null $invoiceAddress invoiceAddress
     *
     * @return self
     */
    public function setInvoiceAddress($invoiceAddress)
    {
        $this->container['invoiceAddress'] = $invoiceAddress;

        return $this;
    }

    /**
     * Gets invoiceAddressEntity
     *
     * @return \WigandtTech\Refurbed\Model\AddressEntityFilter|null
     */
    public function getInvoiceAddressEntity()
    {
        return $this->container['invoiceAddressEntity'];
    }

    /**
     * Sets invoiceAddressEntity
     *
     * @param \WigandtTech\Refurbed\Model\AddressEntityFilter|null $invoiceAddressEntity invoiceAddressEntity
     *
     * @return self
     */
    public function setInvoiceAddressEntity($invoiceAddressEntity)
    {
        $this->container['invoiceAddressEntity'] = $invoiceAddressEntity;

        return $this;
    }

    /**
     * Gets invoiceAddressVatin
     *
     * @return \WigandtTech\Refurbed\Model\OrderAddressVATINFilter|null
     */
    public function getInvoiceAddressVatin()
    {
        return $this->container['invoiceAddressVatin'];
    }

    /**
     * Sets invoiceAddressVatin
     *
     * @param \WigandtTech\Refurbed\Model\OrderAddressVATINFilter|null $invoiceAddressVatin invoiceAddressVatin
     *
     * @return self
     */
    public function setInvoiceAddressVatin($invoiceAddressVatin)
    {
        $this->container['invoiceAddressVatin'] = $invoiceAddressVatin;

        return $this;
    }

    /**
     * Gets invoiceAddressCountryCode
     *
     * @return \WigandtTech\Refurbed\Model\CountryCodeFilter|null
     */
    public function getInvoiceAddressCountryCode()
    {
        return $this->container['invoiceAddressCountryCode'];
    }

    /**
     * Sets invoiceAddressCountryCode
     *
     * @param \WigandtTech\Refurbed\Model\CountryCodeFilter|null $invoiceAddressCountryCode invoiceAddressCountryCode
     *
     * @return self
     */
    public function setInvoiceAddressCountryCode($invoiceAddressCountryCode)
    {
        $this->container['invoiceAddressCountryCode'] = $invoiceAddressCountryCode;

        return $this;
    }

    /**
     * Gets currencyCode
     *
     * @return \WigandtTech\Refurbed\Model\CurrencyCodeFilter|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currencyCode'];
    }

    /**
     * Sets currencyCode
     *
     * @param \WigandtTech\Refurbed\Model\CurrencyCodeFilter|null $currencyCode currencyCode
     *
     * @return self
     */
    public function setCurrencyCode($currencyCode)
    {
        $this->container['currencyCode'] = $currencyCode;

        return $this;
    }

    /**
     * Gets settlementCurrencyCode
     *
     * @return \WigandtTech\Refurbed\Model\CurrencyCodeFilter|null
     */
    public function getSettlementCurrencyCode()
    {
        return $this->container['settlementCurrencyCode'];
    }

    /**
     * Sets settlementCurrencyCode
     *
     * @param \WigandtTech\Refurbed\Model\CurrencyCodeFilter|null $settlementCurrencyCode settlementCurrencyCode
     *
     * @return self
     */
    public function setSettlementCurrencyCode($settlementCurrencyCode)
    {
        $this->container['settlementCurrencyCode'] = $settlementCurrencyCode;

        return $this;
    }

    /**
     * Gets totalCharged
     *
     * @return \WigandtTech\Refurbed\Model\NumericRangeFilter|null
     */
    public function getTotalCharged()
    {
        return $this->container['totalCharged'];
    }

    /**
     * Sets totalCharged
     *
     * @param \WigandtTech\Refurbed\Model\NumericRangeFilter|null $totalCharged totalCharged
     *
     * @return self
     */
    public function setTotalCharged($totalCharged)
    {
        $this->container['totalCharged'] = $totalCharged;

        return $this;
    }

    /**
     * Gets settlementTotalCharged
     *
     * @return \WigandtTech\Refurbed\Model\NumericRangeFilter|null
     */
    public function getSettlementTotalCharged()
    {
        return $this->container['settlementTotalCharged'];
    }

    /**
     * Sets settlementTotalCharged
     *
     * @param \WigandtTech\Refurbed\Model\NumericRangeFilter|null $settlementTotalCharged settlementTotalCharged
     *
     * @return self
     */
    public function setSettlementTotalCharged($settlementTotalCharged)
    {
        $this->container['settlementTotalCharged'] = $settlementTotalCharged;

        return $this;
    }

    /**
     * Gets totalPaid
     *
     * @return \WigandtTech\Refurbed\Model\NumericRangeFilter|null
     */
    public function getTotalPaid()
    {
        return $this->container['totalPaid'];
    }

    /**
     * Sets totalPaid
     *
     * @param \WigandtTech\Refurbed\Model\NumericRangeFilter|null $totalPaid totalPaid
     *
     * @return self
     */
    public function setTotalPaid($totalPaid)
    {
        $this->container['totalPaid'] = $totalPaid;

        return $this;
    }

    /**
     * Gets settlementTotalPaid
     *
     * @return \WigandtTech\Refurbed\Model\NumericRangeFilter|null
     */
    public function getSettlementTotalPaid()
    {
        return $this->container['settlementTotalPaid'];
    }

    /**
     * Sets settlementTotalPaid
     *
     * @param \WigandtTech\Refurbed\Model\NumericRangeFilter|null $settlementTotalPaid settlementTotalPaid
     *
     * @return self
     */
    public function setSettlementTotalPaid($settlementTotalPaid)
    {
        $this->container['settlementTotalPaid'] = $settlementTotalPaid;

        return $this;
    }

    /**
     * Gets totalRefunded
     *
     * @return \WigandtTech\Refurbed\Model\NumericRangeFilter|null
     */
    public function getTotalRefunded()
    {
        return $this->container['totalRefunded'];
    }

    /**
     * Sets totalRefunded
     *
     * @param \WigandtTech\Refurbed\Model\NumericRangeFilter|null $totalRefunded totalRefunded
     *
     * @return self
     */
    public function setTotalRefunded($totalRefunded)
    {
        $this->container['totalRefunded'] = $totalRefunded;

        return $this;
    }

    /**
     * Gets settlementTotalRefunded
     *
     * @return \WigandtTech\Refurbed\Model\NumericRangeFilter|null
     */
    public function getSettlementTotalRefunded()
    {
        return $this->container['settlementTotalRefunded'];
    }

    /**
     * Sets settlementTotalRefunded
     *
     * @param \WigandtTech\Refurbed\Model\NumericRangeFilter|null $settlementTotalRefunded settlementTotalRefunded
     *
     * @return self
     */
    public function setSettlementTotalRefunded($settlementTotalRefunded)
    {
        $this->container['settlementTotalRefunded'] = $settlementTotalRefunded;

        return $this;
    }

    /**
     * Gets isInvoiceable
     *
     * @return \WigandtTech\Refurbed\Model\BoolFilter|null
     */
    public function getIsInvoiceable()
    {
        return $this->container['isInvoiceable'];
    }

    /**
     * Sets isInvoiceable
     *
     * @param \WigandtTech\Refurbed\Model\BoolFilter|null $isInvoiceable isInvoiceable
     *
     * @return self
     */
    public function setIsInvoiceable($isInvoiceable)
    {
        $this->container['isInvoiceable'] = $isInvoiceable;

        return $this;
    }

    /**
     * Gets hasInvoice
     *
     * @return \WigandtTech\Refurbed\Model\BoolFilter|null
     */
    public function getHasInvoice()
    {
        return $this->container['hasInvoice'];
    }

    /**
     * Sets hasInvoice
     *
     * @param \WigandtTech\Refurbed\Model\BoolFilter|null $hasInvoice hasInvoice
     *
     * @return self
     */
    public function setHasInvoice($hasInvoice)
    {
        $this->container['hasInvoice'] = $hasInvoice;

        return $this;
    }

    /**
     * Gets itemName
     *
     * @return \WigandtTech\Refurbed\Model\ListOrdersRequestFilterOrderItemNameFilter|null
     */
    public function getItemName()
    {
        return $this->container['itemName'];
    }

    /**
     * Sets itemName
     *
     * @param \WigandtTech\Refurbed\Model\ListOrdersRequestFilterOrderItemNameFilter|null $itemName itemName
     *
     * @return self
     */
    public function setItemName($itemName)
    {
        $this->container['itemName'] = $itemName;

        return $this;
    }

    /**
     * Gets itemSku
     *
     * @return \WigandtTech\Refurbed\Model\OfferSKUFilter|null
     */
    public function getItemSku()
    {
        return $this->container['itemSku'];
    }

    /**
     * Sets itemSku
     *
     * @param \WigandtTech\Refurbed\Model\OfferSKUFilter|null $itemSku itemSku
     *
     * @return self
     */
    public function setItemSku($itemSku)
    {
        $this->container['itemSku'] = $itemSku;

        return $this;
    }

    /**
     * Gets itemOfferId
     *
     * @return \WigandtTech\Refurbed\Model\Int64Filter|null
     */
    public function getItemOfferId()
    {
        return $this->container['itemOfferId'];
    }

    /**
     * Sets itemOfferId
     *
     * @param \WigandtTech\Refurbed\Model\Int64Filter|null $itemOfferId itemOfferId
     *
     * @return self
     */
    public function setItemOfferId($itemOfferId)
    {
        $this->container['itemOfferId'] = $itemOfferId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


