<?php
/**
 * ListMarketOffersByOfferRequestSortBy
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WigandtTech\Refurbed\Model;
use \WigandtTech\Refurbed\ObjectSerializer;

/**
 * ListMarketOffersByOfferRequestSortBy Class Doc Comment
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ListMarketOffersByOfferRequestSortBy
{
    /**
     * Possible values of this enum
     */
    const ID = 'ID';

    const MARKET_PRICE_MARKET_CODE = 'MARKET_PRICE_MARKET_CODE';

    const MARKET_PRICE_MARKET_NAME = 'MARKET_PRICE_MARKET_NAME';

    const MARKET_PRICE_IS_SITE_MARKET = 'MARKET_PRICE_IS_SITE_MARKET';

    const MARKET_PRICE_IS_CALCULATED = 'MARKET_PRICE_IS_CALCULATED';

    const MARKET_PRICE_CURRENCY_CODE = 'MARKET_PRICE_CURRENCY_CODE';

    const MARKET_PRICE_PRICE = 'MARKET_PRICE_PRICE';

    const MARKET_PRICE_MIN_PRICE = 'MARKET_PRICE_MIN_PRICE';

    const MARKET_PRICE_SITE_MARKET_CURRENCY_CODE = 'MARKET_PRICE_SITE_MARKET_CURRENCY_CODE';

    const MARKET_PRICE_SITE_MARKET_PRICE = 'MARKET_PRICE_SITE_MARKET_PRICE';

    const MARKET_PRICE_SITE_MARKET_MIN_PRICE = 'MARKET_PRICE_SITE_MARKET_MIN_PRICE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ID,
            self::MARKET_PRICE_MARKET_CODE,
            self::MARKET_PRICE_MARKET_NAME,
            self::MARKET_PRICE_IS_SITE_MARKET,
            self::MARKET_PRICE_IS_CALCULATED,
            self::MARKET_PRICE_CURRENCY_CODE,
            self::MARKET_PRICE_PRICE,
            self::MARKET_PRICE_MIN_PRICE,
            self::MARKET_PRICE_SITE_MARKET_CURRENCY_CODE,
            self::MARKET_PRICE_SITE_MARKET_PRICE,
            self::MARKET_PRICE_SITE_MARKET_MIN_PRICE
        ];
    }
}


