<?php
/**
 * OfferState
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WigandtTech\Refurbed\Model;
use \WigandtTech\Refurbed\ObjectSerializer;

/**
 * OfferState Class Doc Comment
 *
 * @category Class
 * @description - OK: Everything is in order.  - UNVERIFIED: Offer needs to be verified in the refurbed merchant interface before being shown publicly. This state is set on all offers that are created using GTIN identifiers.
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OfferState
{
    /**
     * Possible values of this enum
     */
    const UNSPECIFIED = 'UNSPECIFIED';

    const OK = 'OK';

    const UNVERIFIED = 'UNVERIFIED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNSPECIFIED,
            self::OK,
            self::UNVERIFIED
        ];
    }
}


