<?php
/**
 * Order
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WigandtTech\Refurbed\Model;

use \ArrayAccess;
use \WigandtTech\Refurbed\ObjectSerializer;

/**
 * Order Class Doc Comment
 *
 * @category Class
 * @description An order.
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Order implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Order';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'releasedAt' => '\DateTime',
        'state' => '\WigandtTech\Refurbed\Model\OrderState',
        'labels' => '\WigandtTech\Refurbed\Model\OrderLabel[]',
        'customerEmail' => 'string',
        'shippingAddress' => '\WigandtTech\Refurbed\Model\Address',
        'invoiceAddress' => '\WigandtTech\Refurbed\Model\Address',
        'currencyCode' => '\WigandtTech\Refurbed\Model\CurrencyCode',
        'settlementCurrencyCode' => '\WigandtTech\Refurbed\Model\CurrencyCode',
        'settlementExchangeRate' => 'string',
        'totalCharged' => 'string',
        'settlementTotalCharged' => 'string',
        'totalPaid' => 'string',
        'settlementTotalPaid' => 'string',
        'totalRefunded' => 'string',
        'settlementTotalRefunded' => 'string',
        'isRefundable' => 'bool',
        'isInvoiceable' => 'bool',
        'hasInvoice' => 'bool',
        'items' => '\WigandtTech\Refurbed\Model\OrderItem[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'releasedAt' => 'date-time',
        'state' => null,
        'labels' => null,
        'customerEmail' => null,
        'shippingAddress' => null,
        'invoiceAddress' => null,
        'currencyCode' => null,
        'settlementCurrencyCode' => null,
        'settlementExchangeRate' => null,
        'totalCharged' => null,
        'settlementTotalCharged' => null,
        'totalPaid' => null,
        'settlementTotalPaid' => null,
        'totalRefunded' => null,
        'settlementTotalRefunded' => null,
        'isRefundable' => null,
        'isInvoiceable' => null,
        'hasInvoice' => null,
        'items' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'releasedAt' => 'released_at',
        'state' => 'state',
        'labels' => 'labels',
        'customerEmail' => 'customer_email',
        'shippingAddress' => 'shipping_address',
        'invoiceAddress' => 'invoice_address',
        'currencyCode' => 'currency_code',
        'settlementCurrencyCode' => 'settlement_currency_code',
        'settlementExchangeRate' => 'settlement_exchange_rate',
        'totalCharged' => 'total_charged',
        'settlementTotalCharged' => 'settlement_total_charged',
        'totalPaid' => 'total_paid',
        'settlementTotalPaid' => 'settlement_total_paid',
        'totalRefunded' => 'total_refunded',
        'settlementTotalRefunded' => 'settlement_total_refunded',
        'isRefundable' => 'is_refundable',
        'isInvoiceable' => 'is_invoiceable',
        'hasInvoice' => 'has_invoice',
        'items' => 'items'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'releasedAt' => 'setReleasedAt',
        'state' => 'setState',
        'labels' => 'setLabels',
        'customerEmail' => 'setCustomerEmail',
        'shippingAddress' => 'setShippingAddress',
        'invoiceAddress' => 'setInvoiceAddress',
        'currencyCode' => 'setCurrencyCode',
        'settlementCurrencyCode' => 'setSettlementCurrencyCode',
        'settlementExchangeRate' => 'setSettlementExchangeRate',
        'totalCharged' => 'setTotalCharged',
        'settlementTotalCharged' => 'setSettlementTotalCharged',
        'totalPaid' => 'setTotalPaid',
        'settlementTotalPaid' => 'setSettlementTotalPaid',
        'totalRefunded' => 'setTotalRefunded',
        'settlementTotalRefunded' => 'setSettlementTotalRefunded',
        'isRefundable' => 'setIsRefundable',
        'isInvoiceable' => 'setIsInvoiceable',
        'hasInvoice' => 'setHasInvoice',
        'items' => 'setItems'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'releasedAt' => 'getReleasedAt',
        'state' => 'getState',
        'labels' => 'getLabels',
        'customerEmail' => 'getCustomerEmail',
        'shippingAddress' => 'getShippingAddress',
        'invoiceAddress' => 'getInvoiceAddress',
        'currencyCode' => 'getCurrencyCode',
        'settlementCurrencyCode' => 'getSettlementCurrencyCode',
        'settlementExchangeRate' => 'getSettlementExchangeRate',
        'totalCharged' => 'getTotalCharged',
        'settlementTotalCharged' => 'getSettlementTotalCharged',
        'totalPaid' => 'getTotalPaid',
        'settlementTotalPaid' => 'getSettlementTotalPaid',
        'totalRefunded' => 'getTotalRefunded',
        'settlementTotalRefunded' => 'getSettlementTotalRefunded',
        'isRefundable' => 'getIsRefundable',
        'isInvoiceable' => 'getIsInvoiceable',
        'hasInvoice' => 'getHasInvoice',
        'items' => 'getItems'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['releasedAt'] = $data['releasedAt'] ?? null;
        $this->container['state'] = $data['state'] ?? null;
        $this->container['labels'] = $data['labels'] ?? null;
        $this->container['customerEmail'] = $data['customerEmail'] ?? null;
        $this->container['shippingAddress'] = $data['shippingAddress'] ?? null;
        $this->container['invoiceAddress'] = $data['invoiceAddress'] ?? null;
        $this->container['currencyCode'] = $data['currencyCode'] ?? null;
        $this->container['settlementCurrencyCode'] = $data['settlementCurrencyCode'] ?? null;
        $this->container['settlementExchangeRate'] = $data['settlementExchangeRate'] ?? null;
        $this->container['totalCharged'] = $data['totalCharged'] ?? null;
        $this->container['settlementTotalCharged'] = $data['settlementTotalCharged'] ?? null;
        $this->container['totalPaid'] = $data['totalPaid'] ?? null;
        $this->container['settlementTotalPaid'] = $data['settlementTotalPaid'] ?? null;
        $this->container['totalRefunded'] = $data['totalRefunded'] ?? null;
        $this->container['settlementTotalRefunded'] = $data['settlementTotalRefunded'] ?? null;
        $this->container['isRefundable'] = $data['isRefundable'] ?? null;
        $this->container['isInvoiceable'] = $data['isInvoiceable'] ?? null;
        $this->container['hasInvoice'] = $data['hasInvoice'] ?? null;
        $this->container['items'] = $data['items'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Primary key.
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets releasedAt
     *
     * @return \DateTime|null
     */
    public function getReleasedAt()
    {
        return $this->container['releasedAt'];
    }

    /**
     * Sets releasedAt
     *
     * @param \DateTime|null $releasedAt When the order was released to the merchant.
     *
     * @return self
     */
    public function setReleasedAt($releasedAt)
    {
        $this->container['releasedAt'] = $releasedAt;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \WigandtTech\Refurbed\Model\OrderState|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \WigandtTech\Refurbed\Model\OrderState|null $state state
     *
     * @return self
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return \WigandtTech\Refurbed\Model\OrderLabel[]|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \WigandtTech\Refurbed\Model\OrderLabel[]|null $labels Order labels.
     *
     * @return self
     */
    public function setLabels($labels)
    {
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets customerEmail
     *
     * @return string|null
     */
    public function getCustomerEmail()
    {
        return $this->container['customerEmail'];
    }

    /**
     * Sets customerEmail
     *
     * @param string|null $customerEmail The customer's email address.
     *
     * @return self
     */
    public function setCustomerEmail($customerEmail)
    {
        $this->container['customerEmail'] = $customerEmail;

        return $this;
    }

    /**
     * Gets shippingAddress
     *
     * @return \WigandtTech\Refurbed\Model\Address|null
     */
    public function getShippingAddress()
    {
        return $this->container['shippingAddress'];
    }

    /**
     * Sets shippingAddress
     *
     * @param \WigandtTech\Refurbed\Model\Address|null $shippingAddress shippingAddress
     *
     * @return self
     */
    public function setShippingAddress($shippingAddress)
    {
        $this->container['shippingAddress'] = $shippingAddress;

        return $this;
    }

    /**
     * Gets invoiceAddress
     *
     * @return \WigandtTech\Refurbed\Model\Address|null
     */
    public function getInvoiceAddress()
    {
        return $this->container['invoiceAddress'];
    }

    /**
     * Sets invoiceAddress
     *
     * @param \WigandtTech\Refurbed\Model\Address|null $invoiceAddress invoiceAddress
     *
     * @return self
     */
    public function setInvoiceAddress($invoiceAddress)
    {
        $this->container['invoiceAddress'] = $invoiceAddress;

        return $this;
    }

    /**
     * Gets currencyCode
     *
     * @return \WigandtTech\Refurbed\Model\CurrencyCode|null
     */
    public function getCurrencyCode()
    {
        return $this->container['currencyCode'];
    }

    /**
     * Sets currencyCode
     *
     * @param \WigandtTech\Refurbed\Model\CurrencyCode|null $currencyCode currencyCode
     *
     * @return self
     */
    public function setCurrencyCode($currencyCode)
    {
        $this->container['currencyCode'] = $currencyCode;

        return $this;
    }

    /**
     * Gets settlementCurrencyCode
     *
     * @return \WigandtTech\Refurbed\Model\CurrencyCode|null
     */
    public function getSettlementCurrencyCode()
    {
        return $this->container['settlementCurrencyCode'];
    }

    /**
     * Sets settlementCurrencyCode
     *
     * @param \WigandtTech\Refurbed\Model\CurrencyCode|null $settlementCurrencyCode settlementCurrencyCode
     *
     * @return self
     */
    public function setSettlementCurrencyCode($settlementCurrencyCode)
    {
        $this->container['settlementCurrencyCode'] = $settlementCurrencyCode;

        return $this;
    }

    /**
     * Gets settlementExchangeRate
     *
     * @return string|null
     */
    public function getSettlementExchangeRate()
    {
        return $this->container['settlementExchangeRate'];
    }

    /**
     * Sets settlementExchangeRate
     *
     * @param string|null $settlementExchangeRate Exchange rate applied to convert amounts from currency to settlement currency.
     *
     * @return self
     */
    public function setSettlementExchangeRate($settlementExchangeRate)
    {
        $this->container['settlementExchangeRate'] = $settlementExchangeRate;

        return $this;
    }

    /**
     * Gets totalCharged
     *
     * @return string|null
     */
    public function getTotalCharged()
    {
        return $this->container['totalCharged'];
    }

    /**
     * Sets totalCharged
     *
     * @param string|null $totalCharged The total amount the customer was charged. This is the sum of all of the order item's total charged values; it is also the sum of total paid and total refunded.
     *
     * @return self
     */
    public function setTotalCharged($totalCharged)
    {
        $this->container['totalCharged'] = $totalCharged;

        return $this;
    }

    /**
     * Gets settlementTotalCharged
     *
     * @return string|null
     */
    public function getSettlementTotalCharged()
    {
        return $this->container['settlementTotalCharged'];
    }

    /**
     * Sets settlementTotalCharged
     *
     * @param string|null $settlementTotalCharged The total amount the customer was charged, in settlement currency.
     *
     * @return self
     */
    public function setSettlementTotalCharged($settlementTotalCharged)
    {
        $this->container['settlementTotalCharged'] = $settlementTotalCharged;

        return $this;
    }

    /**
     * Gets totalPaid
     *
     * @return string|null
     */
    public function getTotalPaid()
    {
        return $this->container['totalPaid'];
    }

    /**
     * Sets totalPaid
     *
     * @param string|null $totalPaid The total amount the user paid for this order. This is the sum of all the order item's total paid values.
     *
     * @return self
     */
    public function setTotalPaid($totalPaid)
    {
        $this->container['totalPaid'] = $totalPaid;

        return $this;
    }

    /**
     * Gets settlementTotalPaid
     *
     * @return string|null
     */
    public function getSettlementTotalPaid()
    {
        return $this->container['settlementTotalPaid'];
    }

    /**
     * Sets settlementTotalPaid
     *
     * @param string|null $settlementTotalPaid The total amount the user paid for this order, in settlement currency.
     *
     * @return self
     */
    public function setSettlementTotalPaid($settlementTotalPaid)
    {
        $this->container['settlementTotalPaid'] = $settlementTotalPaid;

        return $this;
    }

    /**
     * Gets totalRefunded
     *
     * @return string|null
     */
    public function getTotalRefunded()
    {
        return $this->container['totalRefunded'];
    }

    /**
     * Sets totalRefunded
     *
     * @param string|null $totalRefunded The total amount the customer was refunded. This is the sum of all of the order item's total refunded values.
     *
     * @return self
     */
    public function setTotalRefunded($totalRefunded)
    {
        $this->container['totalRefunded'] = $totalRefunded;

        return $this;
    }

    /**
     * Gets settlementTotalRefunded
     *
     * @return string|null
     */
    public function getSettlementTotalRefunded()
    {
        return $this->container['settlementTotalRefunded'];
    }

    /**
     * Sets settlementTotalRefunded
     *
     * @param string|null $settlementTotalRefunded The total amount the customer was refunded, in settlement currency.
     *
     * @return self
     */
    public function setSettlementTotalRefunded($settlementTotalRefunded)
    {
        $this->container['settlementTotalRefunded'] = $settlementTotalRefunded;

        return $this;
    }

    /**
     * Gets isRefundable
     *
     * @return bool|null
     */
    public function getIsRefundable()
    {
        return $this->container['isRefundable'];
    }

    /**
     * Sets isRefundable
     *
     * @param bool|null $isRefundable Indicates whether this order is currently refundable.
     *
     * @return self
     */
    public function setIsRefundable($isRefundable)
    {
        $this->container['isRefundable'] = $isRefundable;

        return $this;
    }

    /**
     * Gets isInvoiceable
     *
     * @return bool|null
     */
    public function getIsInvoiceable()
    {
        return $this->container['isInvoiceable'];
    }

    /**
     * Sets isInvoiceable
     *
     * @param bool|null $isInvoiceable Indicates whether an invoice can be uploaded. Will turn false ~30 days after order release.
     *
     * @return self
     */
    public function setIsInvoiceable($isInvoiceable)
    {
        $this->container['isInvoiceable'] = $isInvoiceable;

        return $this;
    }

    /**
     * Gets hasInvoice
     *
     * @return bool|null
     */
    public function getHasInvoice()
    {
        return $this->container['hasInvoice'];
    }

    /**
     * Sets hasInvoice
     *
     * @param bool|null $hasInvoice Indicates whether an invoice was uploaded.
     *
     * @return self
     */
    public function setHasInvoice($hasInvoice)
    {
        $this->container['hasInvoice'] = $hasInvoice;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \WigandtTech\Refurbed\Model\OrderItem[]|null
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \WigandtTech\Refurbed\Model\OrderItem[]|null $items All items of this order.
     *
     * @return self
     */
    public function setItems($items)
    {
        $this->container['items'] = $items;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


