<?php
/**
 * OrderState
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WigandtTech\Refurbed\Model;
use \WigandtTech\Refurbed\ObjectSerializer;

/**
 * OrderState Class Doc Comment
 *
 * @category Class
 * @description Order states are calculated based on the individual order item states.   - NEW: Order was not handled yet. At least one order item has state NEW.  - REJECTED: Order was rejected (cannot be fulfilled). All order items have state REJECTED.  - CANCELLED: Order was cancelled. All order items have state CANCELLED.  - ACCEPTED: Order was accepted. At least one order item has state ACCEPTED, and none of the other items still have state NEW.  - SHIPPED: Order was fully shipped. All order items have state SHIPPED.  - RETURNED: Order was fully returned. All order items have state RETURNED.
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderState
{
    /**
     * Possible values of this enum
     */
    public const UNSPECIFIED = 'UNSPECIFIED';

    public const _NEW = 'NEW';

    public const REJECTED = 'REJECTED';

    public const CANCELLED = 'CANCELLED';

    public const ACCEPTED = 'ACCEPTED';

    public const SHIPPED = 'SHIPPED';

    public const RETURNED = 'RETURNED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNSPECIFIED,
            self::_NEW,
            self::REJECTED,
            self::CANCELLED,
            self::ACCEPTED,
            self::SHIPPED,
            self::RETURNED
        ];
    }
}


