<?php
/**
 * OrderLabel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WigandtTech\Refurbed\Model;
use \WigandtTech\Refurbed\ObjectSerializer;

/**
 * OrderLabel Class Doc Comment
 *
 * @category Class
 * @description Labels are additional indicators set next to the order state. They can be filtered by.   - PROCESSING: Set if the items&#39; states of an order are neither all state NEW, nor all a final state.  - PARTIALLY_REJECTED: Set if at least one order item (but not all) has state REJECTED.  - PARTIALLY_CANCELLED: Set if at least one order item (but not all) has state CANCELLED.  - PARTIALLY_SHIPPED: Set if at least one order item (but not all) has state SHIPPED.  - PARTIALLY_RETURNED: Set if at least one order item (but not all) has state RETURNED.  - MISSING_PARCEL_TRACKING_URLS: Set if at least one order item does not have parcel tracking url set.  - MISSING_ITEM_IDENTIFIERS: Set if at least one order item does not have item identifier set.
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderLabel
{
    /**
     * Possible values of this enum
     */
    public const UNSPECIFIED = 'UNSPECIFIED';

    public const PROCESSING = 'PROCESSING';

    public const PARTIALLY_REJECTED = 'PARTIALLY_REJECTED';

    public const PARTIALLY_CANCELLED = 'PARTIALLY_CANCELLED';

    public const PARTIALLY_SHIPPED = 'PARTIALLY_SHIPPED';

    public const PARTIALLY_RETURNED = 'PARTIALLY_RETURNED';

    public const MISSING_PARCEL_TRACKING_URLS = 'MISSING_PARCEL_TRACKING_URLS';

    public const MISSING_ITEM_IDENTIFIERS = 'MISSING_ITEM_IDENTIFIERS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNSPECIFIED,
            self::PROCESSING,
            self::PARTIALLY_REJECTED,
            self::PARTIALLY_CANCELLED,
            self::PARTIALLY_SHIPPED,
            self::PARTIALLY_RETURNED,
            self::MISSING_PARCEL_TRACKING_URLS,
            self::MISSING_ITEM_IDENTIFIERS
        ];
    }
}


