<?php
/**
 * UpdateShippingProfileRequest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace WigandtTech\Refurbed\Model;

use \ArrayAccess;
use \WigandtTech\Refurbed\ObjectSerializer;

/**
 * UpdateShippingProfileRequest Class Doc Comment
 *
 * @category Class
 * @description See shipping profile for full documentation.
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class UpdateShippingProfileRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdateShippingProfileRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'sourceCountryMarketCode' => 'string',
        'createDestinations' => '\WigandtTech\Refurbed\Model\UpdateShippingProfileRequestCreateDestination[]',
        'updateDestinations' => '\WigandtTech\Refurbed\Model\UpdateDestination[]',
        'deleteDestinations' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int64',
        'name' => null,
        'sourceCountryMarketCode' => null,
        'createDestinations' => null,
        'updateDestinations' => null,
        'deleteDestinations' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'sourceCountryMarketCode' => 'source_country_market_code',
        'createDestinations' => 'create_destinations',
        'updateDestinations' => 'update_destinations',
        'deleteDestinations' => 'delete_destinations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'sourceCountryMarketCode' => 'setSourceCountryMarketCode',
        'createDestinations' => 'setCreateDestinations',
        'updateDestinations' => 'setUpdateDestinations',
        'deleteDestinations' => 'setDeleteDestinations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'sourceCountryMarketCode' => 'getSourceCountryMarketCode',
        'createDestinations' => 'getCreateDestinations',
        'updateDestinations' => 'getUpdateDestinations',
        'deleteDestinations' => 'getDeleteDestinations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['sourceCountryMarketCode'] = $data['sourceCountryMarketCode'] ?? null;
        $this->container['createDestinations'] = $data['createDestinations'] ?? null;
        $this->container['updateDestinations'] = $data['updateDestinations'] ?? null;
        $this->container['deleteDestinations'] = $data['deleteDestinations'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets sourceCountryMarketCode
     *
     * @return string|null
     */
    public function getSourceCountryMarketCode()
    {
        return $this->container['sourceCountryMarketCode'];
    }

    /**
     * Sets sourceCountryMarketCode
     *
     * @param string|null $sourceCountryMarketCode sourceCountryMarketCode
     *
     * @return self
     */
    public function setSourceCountryMarketCode($sourceCountryMarketCode)
    {
        $this->container['sourceCountryMarketCode'] = $sourceCountryMarketCode;

        return $this;
    }

    /**
     * Gets createDestinations
     *
     * @return \WigandtTech\Refurbed\Model\UpdateShippingProfileRequestCreateDestination[]|null
     */
    public function getCreateDestinations()
    {
        return $this->container['createDestinations'];
    }

    /**
     * Sets createDestinations
     *
     * @param \WigandtTech\Refurbed\Model\UpdateShippingProfileRequestCreateDestination[]|null $createDestinations Destinations to create.
     *
     * @return self
     */
    public function setCreateDestinations($createDestinations)
    {
        $this->container['createDestinations'] = $createDestinations;

        return $this;
    }

    /**
     * Gets updateDestinations
     *
     * @return \WigandtTech\Refurbed\Model\UpdateDestination[]|null
     */
    public function getUpdateDestinations()
    {
        return $this->container['updateDestinations'];
    }

    /**
     * Sets updateDestinations
     *
     * @param \WigandtTech\Refurbed\Model\UpdateDestination[]|null $updateDestinations Destinations to update.
     *
     * @return self
     */
    public function setUpdateDestinations($updateDestinations)
    {
        $this->container['updateDestinations'] = $updateDestinations;

        return $this;
    }

    /**
     * Gets deleteDestinations
     *
     * @return string[]|null
     */
    public function getDeleteDestinations()
    {
        return $this->container['deleteDestinations'];
    }

    /**
     * Sets deleteDestinations
     *
     * @param string[]|null $deleteDestinations Destinations to delete. Takes a list of market codes.
     *
     * @return self
     */
    public function setDeleteDestinations($deleteDestinations)
    {
        $this->container['deleteDestinations'] = $deleteDestinations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


