<?php
/**
 * OfferDataTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace WigandtTech\Refurbed\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OfferDataTest Class Doc Comment
 *
 * @category    Class
 * @description OfferData
 * @package     WigandtTech\Refurbed
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OfferDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OfferData"
     */
    public function testOfferData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "offerId"
     */
    public function testPropertyOfferId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "offerVersion"
     */
    public function testPropertyOfferVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "offerOrderExchangeRate"
     */
    public function testPropertyOfferOrderExchangeRate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "offerWarranty"
     */
    public function testPropertyOfferWarranty()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "offerGrading"
     */
    public function testPropertyOfferGrading()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shippingProfileId"
     */
    public function testPropertyShippingProfileId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shippingProfileVersion"
     */
    public function testPropertyShippingProfileVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shippingCosts"
     */
    public function testPropertyShippingCosts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
