<?php
/**
 * MarketOfferServiceApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace WigandtTech\Refurbed\Test\Api;

use \WigandtTech\Refurbed\Configuration;
use \WigandtTech\Refurbed\ApiException;
use \WigandtTech\Refurbed\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MarketOfferServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MarketOfferServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for batchCreateMarketOffer
     *
     * Batch creates market offers / offer market prices of offers..
     *
     */
    public function testBatchCreateMarketOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for batchDeleteMarketOffer
     *
     * Batch deletes market offers / offer market prices of offers..
     *
     */
    public function testBatchDeleteMarketOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for batchGetMarketOffer
     *
     * Batch gets market offers / offer market prices of offers..
     *
     */
    public function testBatchGetMarketOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for batchUpdateMarketOffer
     *
     * Batch updates market offers / offer market prices of offers..
     *
     */
    public function testBatchUpdateMarketOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createMarketOffer
     *
     * Creates a single market offer / an offer market price of an offer..
     *
     */
    public function testCreateMarketOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMarketOffer
     *
     * Deletes a single market offer / an offer market price of an offer..
     *
     */
    public function testDeleteMarketOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMarketOffer
     *
     * Gets a single market offer..
     *
     */
    public function testGetMarketOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMarketOffers
     *
     * Lists all market offers..
     *
     */
    public function testListMarketOffers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMarketOffersByOffer
     *
     * Lists all market offers of a specific offer and version..
     *
     */
    public function testListMarketOffersByOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMarketOffer
     *
     * Updates a single market offer / an offer market price of an offer..
     *
     */
    public function testUpdateMarketOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
