<?php
/**
 * ShippingProfileServiceApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant API
 *
 * The refurbed merchant API allows to access and manage markets, currencies, instances, shipping profiles, offers, market offers, orders and order items.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: integrations@refurbed.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace WigandtTech\Refurbed\Test\Api;

use \WigandtTech\Refurbed\Configuration;
use \WigandtTech\Refurbed\ApiException;
use \WigandtTech\Refurbed\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ShippingProfileServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  WigandtTech\Refurbed
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShippingProfileServiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createShippingProfile
     *
     * Creates a shipping profile..
     *
     */
    public function testCreateShippingProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteShippingProfile
     *
     * Deletes a shipping profile. Only shipping profiles marked as deletable can be deleted..
     *
     */
    public function testDeleteShippingProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShippingProfile
     *
     * Gets a single shipping profile. If no version is defined, its current version is returned..
     *
     */
    public function testGetShippingProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listShippingProfiles
     *
     * Lists all current shipping profiles..
     *
     */
    public function testListShippingProfiles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateShippingProfile
     *
     * Updates a shipping profile..
     *
     */
    public function testUpdateShippingProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
